[package]
name = "memorama"
version = "0.1.0"
authors = ["Enrique Bermúdez <enrique.bermudez@4rsoluciones.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"